import operator
from typing_extensions import Annotated, TypedDict


class ResearchTask(TypedDict):
    '''Research task generated by planner'''
    task_id: str
    description: str
    search_queries: list[str]
    output_schema: dict
    status: str

class TaskResult(TypedDict):
    '''Result from a completed task'''
    task_id: str
    search_results: list[dict]
    reasoning: str
    structured_output: dict
    citations: list[str]
    key_insights: list[str]

class ResearchState(TypedDict):
    '''Main state that flows through the graph'''
    query: str

    research_plan: str
    tasks: list[ResearchTask]

    task_results: Annotated[list[TaskResult], operator.add]

    full_context: str
    final_output: dict

    total_tokens_used: int
    execution_time: float

    iteration_count: int
    max_iterations: int
    research_complete: bool
    identified_gaps: list[str]
    follow_up_tasks: list[ResearchTask]
